name: Setup GitHub Runner

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Initialize Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          LINUX_HOST: ${{ secrets.LINUX_HOST }}
          LINUX_USER: ${{ secrets.LINUX_USER }}
          LINUX_PASSWORD: ${{ secrets.LINUX_PASSWORD }}
        run: terraform init

      - name: Apply Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_linux_host: ${{ secrets.LINUX_HOST }}
          TF_VAR_linux_user: ${{ secrets.LINUX_USER }}
          TF_VAR_linux_password: ${{ secrets.LINUX_PASSWORD }}
        run: terraform apply -auto-approve
